check50:
  checks:
    input of 1 yields correct output:
      - run: python3 mario.py
        stdin: 1
        stdout: "#"
    input of 2 yields correct output:
      - run: python3 mario.py
        stdin: 2
        stdout: " #\n##"
    input of 5 yields correct output:
      - run: python3 mario.py
        stdin: 5
        stdout: "    #\n   ##\n  ###\n ####\n#####"
    input of 8 yields correct output:
      - run: python3 mario.py
        stdin: 8
        stdout: "       #\n      ##\n     ###\n    ####\n   #####\n  ######\n #######\n########"
    input of hello does not output:
      - run: python3 mario.py
        stdin: hello
        stdout: ""
